import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { formatStockholmDateTime } from "@/features/matches/match-time";
import { loadPlayerProfile, summarizePlayerMatches } from "@/features/players/player-profile";
import { loadTeamContext } from "@/lib/auth/team-context";
import { createClient } from "@/lib/supabase/server";

export const dynamic="force-dynamic";
export default async function PlayerPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{change?:string}>}){
 const {id}=await params; const supabase=await createClient(); const {data}=await supabase.auth.getClaims(); if(!data?.claims?.sub)redirect(`/login?next=${encodeURIComponent(`/players/${id}`)}`); const context=await loadTeamContext(supabase);if(!context)redirect("/access-denied");const player=await loadPlayerProfile(supabase,context.teamId,context.seasonId,id);if(!player)notFound();const summary=summarizePlayerMatches(player.matches);const query=await searchParams;const selected=player.matches.filter(match=>match.selectionStatus==="selected");const upcoming=selected.filter(match=>match.status==="upcoming");const previous=selected.filter(match=>match.status==="completed").reverse();const futureAutomatic=upcoming.filter(match=>match.isFuture&&match.selectionType==="regular"&&match.selectionSource==="automatic");
 return <AppShell currentItem="Spelare"><main className="mx-auto max-w-2xl"><Link href="/players" className="inline-flex min-h-11 items-center text-sm font-semibold text-blue-700">← Till spelare</Link><section className="mt-2 rounded-2xl bg-white p-5 shadow-sm">{query.change?<p role="status" className="mb-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">{query.change==="created"?"Spelaren är tillagd.":query.change==="deactivated"?"Spelaren är deaktiverad.":"Spelaren är uppdaterad."}</p>:null}<div className="flex items-start justify-between gap-4"><div><h1 className="text-3xl font-bold text-slate-950">{player.name}</h1><p className="mt-2 text-slate-600">Nivå {player.level} · {player.isActive?"Aktiv":"Inaktiv"}</p></div>{player.isActive?<Link href={`/players/${id}/edit`} className="inline-flex min-h-11 items-center rounded-xl border border-blue-700 px-4 text-sm font-semibold text-blue-700">Ändra</Link>:null}</div><dl className="mt-6 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-slate-500">Ordinarie</dt><dd className="mt-1 font-semibold">{summary.plannedRegular} planerade · {summary.completedRegular} spelade</dd></div><div><dt className="text-slate-500">Extra inhopp</dt><dd className="mt-1 font-semibold">{summary.plannedExtra} planerade · {summary.completedExtra} spelade</dd></div></dl></section>
 {([['Kommande matcher',upcoming],['Tidigare matcher',previous]] as const).map(([title,matches])=><section key={title} className="mt-6"><h2 className="text-xl font-semibold text-slate-950">{title}</h2>{matches.length===0?<p className="mt-3 rounded-xl bg-white p-4 text-sm text-slate-600">Inga {title.toLocaleLowerCase("sv")}.</p>:<ul className="mt-3 space-y-3">{matches.map(match=><li key={match.id} className="rounded-xl bg-white p-4 shadow-sm"><Link href={`/matches/${match.id}`} className="font-semibold text-blue-700">{match.opponent}</Link><p className="mt-1 text-sm text-slate-600">{formatStockholmDateTime(match.startsAt)}{match.location?` · ${match.location}`:""}</p><span className="mt-2 inline-block rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-700">{match.selectionType==="extra"?"Extra inhoppare":"Ordinarie"}{match.status==="completed"?` · ${match.played?"Spelade":"Deltog inte"}`:""}</span></li>)}</ul>}</section>)}
 {player.isActive?<p className="mt-6 rounded-xl bg-blue-50 p-4 text-sm text-blue-900">Ändringar påverkar inte redan sparade lag. <Link href="/matches/allocation/preview" className="font-semibold underline">Förhandsgranska omfördelning</Link>.</p>:futureAutomatic.length>0?<p className="mt-6 rounded-xl bg-amber-50 p-4 text-sm text-amber-950">Spelaren finns kvar i {futureAutomatic.length} {futureAutomatic.length===1?"automatiskt framtida lag":"automatiska framtida lag"}. <Link href="/matches/allocation/preview" className="font-semibold underline">Förhandsgranska och spara omfördelning</Link>.</p>:null}</main></AppShell>;
}
