import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { loadPlayerProfile } from "@/features/players/player-profile";
import { loadTeamContext } from "@/lib/auth/team-context";
import { createClient } from "@/lib/supabase/server";
import { PlayerForm } from "../../player-form";

export const dynamic="force-dynamic";
export default async function EditPlayerPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string}>}){
 const {id}=await params;const supabase=await createClient();const {data}=await supabase.auth.getClaims();if(!data?.claims?.sub)redirect(`/login?next=${encodeURIComponent(`/players/${id}/edit`)}`);const context=await loadTeamContext(supabase);if(!context)redirect("/access-denied");const player=await loadPlayerProfile(supabase,context.teamId,context.seasonId,id);if(!player)notFound();if(!player.isActive)redirect(`/players/${id}`);const error=(await searchParams).error;const blockers=player.matches.filter(match=>match.status==="upcoming"&&match.isFuture&&(match.selectionSource==="manual"||match.selectionType==="extra"));const automatic=player.matches.filter(match=>match.status==="upcoming"&&match.isFuture&&match.selectionType==="regular"&&match.selectionSource==="automatic"&&match.selectionStatus==="selected");
 return <AppShell currentItem="Spelare"><main className="mx-auto max-w-xl"><Link href={`/players/${id}`} className="inline-flex min-h-11 items-center text-sm font-semibold text-blue-700">← Till spelaren</Link><h1 className="mt-2 text-3xl font-bold text-slate-950">Ändra spelare</h1>{error?<p role="alert" className="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-950">{error==="stale"?"Spelaren ändrades av en annan tränare. Kontrollera uppgifterna och försök igen.":error==="blocked"?"Hantera de planerade besluten innan spelaren deaktiveras.":"Uppgifterna kunde inte sparas."}</p>:null}<div className="mt-6"><PlayerForm action={`/players/${id}/update`} submitLabel="Spara ändringar" defaults={{firstName:player.firstName,lastName:player.lastName,level:player.level}} fingerprint={player.fingerprint}/></div>
 <section className="mt-8 rounded-2xl border border-red-200 bg-white p-5"><h2 className="text-lg font-semibold text-slate-950">Deaktivera spelare</h2><p className="mt-2 text-sm text-slate-600">Historiken bevaras, men spelaren tas inte med i nya uttagningar.</p>{blockers.length>0?<div className="mt-4 rounded-xl bg-amber-50 p-4"><p className="text-sm font-semibold text-amber-950">Följande matcher måste hanteras först:</p><ul className="mt-2 space-y-2">{blockers.map(match=><li key={`${match.id}-${match.selectionStatus}`}><Link href={`/matches/${match.id}`} className="text-sm font-semibold text-blue-700 underline">{match.opponent} – {match.selectionType==="extra"?"ta bort extra inhoppare":"återställ manuellt byte"}</Link></li>)}</ul></div>:<form action={`/players/${id}/deactivate`} method="post" className="mt-4"><input type="hidden" name="fingerprint" value={player.fingerprint}/>{automatic.length>0?<p className="mb-3 text-sm text-amber-900">Spelaren finns i {automatic.length} automatiska framtida lag. Omfördela efter deaktiveringen.</p>:null}<button className="min-h-11 rounded-xl border border-red-400 px-4 font-semibold text-red-800">Ja, deaktivera spelaren</button></form>}</section></main></AppShell>;
}
