"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import type { PlayerListItem } from "./player-list";
const levelStyles = { 1: "bg-emerald-50 text-emerald-800", 2: "bg-amber-50 text-amber-800", 3: "bg-slate-100 text-slate-700" };
export type PlayerSort = "name" | "offered" | "regular" | "extra" | "total" | "planned";
export function sortPlayerOverview(players: PlayerListItem[], sort: PlayerSort) {
  const number = (p: PlayerListItem) => ({ offered: p.offeredRegular ?? 0, regular: p.completedRegular, extra: p.completedExtra, total: p.completedRegular + p.completedExtra, planned: p.plannedRegular, name: 0 })[sort];
  return [...players].sort((a,b) => number(a)-number(b) || a.name.localeCompare(b.name,"sv") || a.id.localeCompare(b.id));
}
export function PlayerListView({ players, seasonName }: { players: PlayerListItem[]; seasonName: string }) {
  const [query, setQuery] = useState("");
  const [sort, setSort] = useState<PlayerSort>("name");
  const visible = useMemo(() => sortPlayerOverview(players.filter(p => p.name.toLocaleLowerCase("sv").includes(query.trim().toLocaleLowerCase("sv"))), sort), [players,query,sort]);
  return <section className="space-y-5" aria-labelledby="players-heading"><header><p className="text-sm text-slate-500">{seasonName}</p><div className="mt-1 flex flex-wrap items-center justify-between gap-3"><h1 id="players-heading" className="text-2xl font-semibold">Spelare</h1><Link href="/players/new" className="inline-flex min-h-11 items-center rounded-xl bg-blue-700 px-4 text-sm font-semibold text-white">Lägg till spelare</Link></div><p className="mt-2 text-sm text-slate-500">{players.length} {players.length === 1 ? "aktiv" : "aktiva"}</p></header>
    {players.length ? <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Sök spelare<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Skriv ett namn" className="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white px-4" /></label><label className="text-sm font-semibold">Sortera, lägst först<select value={sort} onChange={e=>setSort(e.target.value as PlayerSort)} className="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white px-3"><option value="name">Namn</option><option value="offered">Erbjudna ordinarie</option><option value="regular">Spelade ordinarie</option><option value="extra">Spelade extra</option><option value="total">Totalt spelade</option><option value="planned">Framtida planerade</option></select></label></div> : null}
    {players.some(p => p.offeredHistoryComplete === false) ? <p role="status" className="rounded-xl bg-amber-50 p-4 text-sm text-amber-950">Tidigare kallelser är inte fullständigt bekräftade. Erbjudna antal visar endast bekräftade kallelser och kan vara högre när historiken är genomgången.</p> : null}
    {!players.length ? <div className="rounded-2xl bg-white p-6"><h2 className="font-semibold">Inga spelare ännu</h2><Link href="/players/new" className="mt-3 inline-flex min-h-11 items-center font-semibold text-blue-700">Lägg till spelare</Link></div> : !visible.length ? <p className="rounded-xl bg-white p-5">Ingen spelare matchar sökningen.</p> : <>
      <ul className="grid gap-3 lg:hidden" aria-label="Aktiva spelare">{visible.map(p=><li key={p.id}><Link href={`/players/${p.id}`} className="block rounded-2xl bg-white p-4 shadow-sm"><div className="flex items-center justify-between gap-3"><span className="min-w-0 break-words font-semibold">{p.name}</span><span className={`shrink-0 rounded-full px-2 py-1 text-xs ${levelStyles[p.level]}`}>{p.levelLabel}</span></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm">{[[p.offeredHistoryComplete === false ? "Bekräftade ordinarie · ofullständigt" : "Erbjudna ordinarie",p.offeredRegular??0],["Spelade ordinarie",p.completedRegular],["Spelade extra",p.completedExtra],["Totalt spelade",p.completedRegular+p.completedExtra],["Framtida planerade",p.plannedRegular]].map(([label,count])=><div key={label}><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 font-semibold">{count}</dd></div>)}</dl></Link></li>)}</ul>
      <table className="hidden w-full table-fixed rounded-xl bg-white text-sm lg:table"><caption className="py-3 text-left font-semibold">Matchöversikt för aktiva spelare</caption><thead><tr>{["Spelare","Erbjudna ordinarie","Spelade ordinarie","Spelade extra","Totalt spelade","Framtida planerade"].map(label=><th key={label} scope="col" className="break-words p-3 text-left">{label}</th>)}</tr></thead><tbody>{visible.map(p=><tr key={p.id} className="border-t border-slate-100"><th scope="row" className="break-words p-3 text-left font-medium"><Link href={`/players/${p.id}`} className="text-blue-700 underline">{p.name}</Link><span className="mt-1 block text-xs text-slate-500">{p.levelLabel}</span></th>{[p.offeredRegular??0,p.completedRegular,p.completedExtra,p.completedRegular+p.completedExtra,p.plannedRegular].map((count,i)=><td key={i} className="p-3">{count}{i === 0 && p.offeredHistoryComplete === false ? <span className="block text-xs text-amber-800">Ofullständigt</span> : null}</td>)}</tr>)}</tbody></table>
    </>}
    <p className="text-xs text-slate-500">Erbjudna ordinarie räknar skickade kallelser, även vid återbud. Spelade räknar endast låst deltagande. Äldre kallelser behöver bekräftas. Nivå 1 är högst och nivå 3 lägst; nivå används bara för balans.</p>
    <Link href="/matches/history" className="inline-flex min-h-11 items-center text-sm font-semibold text-blue-700">Kontrollera tidigare kallelser</Link>
  </section>;
}
