import Link from "next/link";
import {redirect} from "next/navigation";
import {AppShell} from "@/components/app-shell";
import {MatchupLabel} from "@/components/team-logo";
import {formatStockholmDateTime} from "@/features/matches/match-time";
import {loadOverview} from "@/features/overview/overview";
import {formatTrainingTime} from "@/features/trainings/training-time";
import {trainingStatusText} from "@/features/trainings/training-plans";
import {getVerifiedUserId} from "@/lib/auth/verified-user";
import {createClient} from "@/lib/supabase/server";

export const dynamic="force-dynamic";

export default async function Home(){const supabase=await createClient();const userId=await getVerifiedUserId();if(!userId)redirect("/login");const overview=await loadOverview(supabase);if(!overview)redirect("/access-denied");const next=overview.upcomingMatches[0];const nextTraining=overview.nextTraining;
 return <AppShell currentItem="Kommande" role={overview.role}><div className="mx-auto max-w-2xl"><header><p className="text-sm font-semibold text-blue-700">{overview.seasonName}</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Kommande</h1></header>
 <section className="mt-6"><h2 className="text-xl font-semibold text-slate-950">Nästa match</h2>{next?<article className="mt-3 rounded-2xl bg-[#082B4C] p-5 text-white shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><h3 className="text-xl font-semibold"><MatchupLabel opponent={next.opponent}/></h3><p className="mt-3 text-blue-100">{formatStockholmDateTime(next.startsAt)}</p><p className="mt-1 text-sm text-blue-200">{next.location??"Plats ej angiven"}</p><p className="mt-3 text-sm font-semibold">{next.selectedPlayers} / {next.targetPlayers} uttagna</p></div><Link href={`/matches/${next.id}`} className="inline-flex min-h-11 items-center rounded-xl bg-white px-4 text-sm font-semibold text-[#082B4C]">Visa laget</Link></div></article>:<div className="mt-3 rounded-2xl border border-dashed border-slate-300 bg-white p-6"><p className="font-semibold text-slate-900">Inga kommande matcher</p><p className="mt-2 text-sm text-slate-600">{overview.role==="coach"?"Skapa nästa match för att börja planera laget.":"Det finns ingen planerad match ännu."}</p>{overview.role==="coach"?<Link href="/matches/new" className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-blue-700 px-4 font-semibold text-white">Skapa match</Link>:null}</div>}</section>
 <section className="mt-8"><h2 className="text-xl font-semibold text-slate-950">Nästa träning</h2>{nextTraining?<article className="mt-3 rounded-2xl border-2 border-emerald-300 bg-emerald-50 p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-emerald-700 px-3 py-1 text-xs font-bold uppercase tracking-wide text-white">Block {nextTraining.themeBlock}</span><span className="text-sm font-semibold text-emerald-900">{trainingStatusText(nextTraining.status)}</span></div><h3 className="mt-3 text-xl font-bold text-slate-950">{nextTraining.focus}</h3><p className="mt-2 text-slate-700">{formatTrainingTime(nextTraining.startsAt,nextTraining.endsAt)}</p><p className="mt-3 text-sm font-semibold text-emerald-950">{nextTraining.keyMessage}</p></div><Link href={`/trainings/${nextTraining.id}`} className="inline-flex min-h-11 items-center rounded-xl bg-emerald-700 px-4 text-sm font-semibold text-white">Öppna planeringen</Link></div></article>:<div className="mt-3 rounded-2xl border border-dashed border-slate-300 bg-white p-6"><p className="font-semibold text-slate-900">Ingen kommande träning</p><p className="mt-2 text-sm text-slate-600">Det finns ingen framtida träning i den aktiva säsongen.</p></div>}</section>
 </div></AppShell>;
}
