import Link from "next/link";
import {redirect} from "next/navigation";
import {AppShell} from "@/components/app-shell";
import {MatchupLabel,OpponentLabel} from "@/components/team-logo";
import {formatStockholmDateTime} from "@/features/matches/match-time";
import {groupRegularCounts,hasFairnessWarning,loadOverview} from "@/features/overview/overview";
import {formatTrainingTime} from "@/features/trainings/training-time";
import {trainingStatusText} from "@/features/trainings/training-plans";
import {createClient} from "@/lib/supabase/server";

export const dynamic="force-dynamic";

export default async function Home(){const supabase=await createClient();const {data}=await supabase.auth.getClaims();if(!data?.claims?.sub)redirect("/login");const overview=await loadOverview(supabase);if(!overview)redirect("/access-denied");const next=overview.upcomingMatches[0];const nextTraining=overview.nextTraining;const groups=groupRegularCounts(overview.players);const warning=hasFairnessWarning(overview.players);
 return <AppShell currentItem="Översikt"><div className="mx-auto max-w-4xl"><header><p className="text-sm font-semibold text-blue-700">{overview.seasonName}</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Översikt</h1></header>
 <section className="mt-6"><h2 className="text-xl font-semibold text-slate-950">Nästa match</h2>{next?<article className="mt-3 rounded-2xl bg-[#082B4C] p-5 text-white shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><h3 className="text-xl font-semibold"><MatchupLabel opponent={next.opponent}/></h3><p className="mt-3 text-blue-100">{formatStockholmDateTime(next.startsAt)}</p><p className="mt-1 text-sm text-blue-200">{next.location??"Plats ej angiven"}</p><p className="mt-3 text-sm font-semibold">{next.selectedPlayers} / {next.targetPlayers} uttagna</p></div><Link href={`/matches/${next.id}`} className="inline-flex min-h-11 items-center rounded-xl bg-white px-4 text-sm font-semibold text-[#082B4C]">Visa laget</Link></div></article>:<div className="mt-3 rounded-2xl border border-dashed border-slate-300 bg-white p-6"><p className="font-semibold text-slate-900">Inga kommande matcher</p><p className="mt-2 text-sm text-slate-600">Skapa nästa match för att börja planera laget.</p><Link href="/matches/new" className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-blue-700 px-4 font-semibold text-white">Skapa match</Link></div>}</section>
 <section className="mt-8"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-semibold text-slate-950">Nästa träning</h2><Link href="/trainings" className="text-sm font-semibold text-blue-700">Visa alla</Link></div>{nextTraining?<article className="mt-3 rounded-2xl border-2 border-emerald-300 bg-emerald-50 p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-emerald-700 px-3 py-1 text-xs font-bold uppercase tracking-wide text-white">Block {nextTraining.themeBlock}</span><span className="text-sm font-semibold text-emerald-900">{trainingStatusText(nextTraining.status)}</span></div><h3 className="mt-3 text-xl font-bold text-slate-950">{nextTraining.focus}</h3><p className="mt-2 text-slate-700">{formatTrainingTime(nextTraining.startsAt,nextTraining.endsAt)}</p><p className="mt-3 text-sm font-semibold text-emerald-950">{nextTraining.keyMessage}</p></div><Link href={`/trainings/${nextTraining.id}`} className="inline-flex min-h-11 items-center rounded-xl bg-emerald-700 px-4 text-sm font-semibold text-white">Öppna planeringen</Link></div></article>:<div className="mt-3 rounded-2xl border border-dashed border-slate-300 bg-white p-6"><p className="font-semibold text-slate-900">Ingen kommande träning</p><p className="mt-2 text-sm text-slate-600">Det finns ingen framtida träning i den aktiva säsongen.</p></div>}</section>
 <div className="mt-8 grid gap-8 lg:grid-cols-2"><section><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-semibold text-slate-950">Kommande matcher</h2><Link href="/matches" className="text-sm font-semibold text-blue-700">Visa alla</Link></div>{overview.upcomingMatches.length?<ul className="mt-3 space-y-3">{overview.upcomingMatches.map(match=><li key={match.id}><Link href={`/matches/${match.id}`} className="flex min-h-16 items-center justify-between gap-3 rounded-xl bg-white p-4 shadow-sm ring-1 ring-slate-200/70"><span className="min-w-0"><span className="block font-semibold text-slate-950"><OpponentLabel opponent={match.opponent}/></span><span className="mt-1 block pl-[52px] text-sm text-slate-600">{formatStockholmDateTime(match.startsAt)}</span></span><span className="shrink-0 text-sm font-semibold text-slate-600">{match.selectedPlayers}/{match.targetPlayers}</span></Link></li>)}</ul>:<p className="mt-3 rounded-xl bg-white p-4 text-sm text-slate-600">Inga framtida matcher att visa.</p>}</section>
 <section><h2 className="text-xl font-semibold text-slate-950">Matchfördelning</h2>{overview.players.length?<div className="mt-3 rounded-2xl bg-white p-5 shadow-sm"><ul className="space-y-3">{groups.map(group=><li key={group.regularCount} className="flex items-center justify-between gap-3 border-b border-slate-100 pb-3 last:border-0 last:pb-0"><span className="text-sm text-slate-700">{group.regularCount===1?"1 ordinarie match":`${group.regularCount} ordinarie matcher`}</span><span className="font-semibold text-slate-950">{group.playerCount} spelare</span></li>)}</ul>{warning?<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-950">Fördelningen skiljer mer än en ordinarie match. <Link href="/matches/allocation/preview" className="font-semibold underline">Förhandsgranska omfördelning</Link>.</p>:<p className="mt-4 text-sm text-emerald-800">Den ordinarie fördelningen är jämn.</p>}<p className="mt-3 text-xs text-slate-500">Extra inhopp räknas separat och påverkar inte denna fördelning.</p></div>:<div className="mt-3 rounded-2xl border border-dashed border-slate-300 bg-white p-6"><p className="font-semibold text-slate-900">Inga aktiva spelare</p><Link href="/players/new" className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-blue-700 px-4 font-semibold text-white">Lägg till spelare</Link></div>}</section></div></div></AppShell>;
}
